dist: xenial

language: python

python: 3.7

services:
  - postgresql
  - redis-server
  - docker

addons:
  postgresql: "10"

env:
  global:
  - DJANGO_SETTINGS_MODULE=bing.conf.jenkins
  - SECRET_KEY=dummy
  - DB_PASSWORD=
  - DB_USER=postgres

install:
  - pip install -r requirements/jenkins.txt
  - pip install codecov
  - npm ci
  - npm run build

script:
  - python src/manage.py collectstatic --noinput --link
  - coverage run src/manage.py test src
  - ./bin/release_docker_image.sh

after_success:
  - codecov

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: develop
    tags: true
