# Inspired by https://docs.docker.com/compose/django/
version: '3'

services:
  db:
    # NOTE: No persistent storage configured.
    # See: https://hub.docker.com/_/postgres/
    image: postgres:11

  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=bing.conf.docker
      - SECRET_KEY=${SECRET_KEY:-v1zy5$p*a5s^9_7r!z9d30jyvpa6oj6j(ie#gpt*z=$&ojkwd0}
    ports:
      - 8000:8000
    depends_on:
      - db
