# Generated by Django 2.2 on 2019-04-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "drc_api_root",
                    models.URLField(
                        default="https://ref.tst.vng.cloud/drc/api/v1/",
                        verbose_name="API root",
                    ),
                ),
                (
                    "drc_client_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="client_id"
                    ),
                ),
                (
                    "drc_secret",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="client_id"
                    ),
                ),
            ],
            options={"verbose_name": "APIs configuration"},
        )
    ]
