# Generated by Django 2.2.9 on 2020-03-03 14:30

from django.db import migrations
import django_camunda.fields


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="bingconfig", name="aanvraag_process_key",),
        migrations.AddField(
            model_name="bingconfig",
            name="camunda_process",
            field=django_camunda.fields.ProcessDefinitionField(
                blank=True,
                help_text="ID of the process definition in Camunda",
                max_length=64,
                verbose_name="camunda process to start",
            ),
        ),
    ]
