# Generated by Django 2.2 on 2019-04-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0002_auto_20190429_0924")]

    operations = [
        migrations.CreateModel(
            name="BInGConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zaaktype_aanvraag",
                    models.URLField(verbose_name="Zaaktype aanvraag"),
                ),
                (
                    "zaaktype_vergadering",
                    models.URLField(verbose_name="Zaaktype vergadering"),
                ),
            ],
            options={"verbose_name": "BInG configuratie"},
        )
    ]
