# Generated by Django 2.2.9 on 2020-03-04 12:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0002_auto_20200303_1530")]

    operations = [
        migrations.AddField(
            model_name="bingconfig",
            name="bag_nlx_headers",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        ),
        migrations.AddField(
            model_name="bingconfig",
            name="bag_root",
            field=models.URLField(
                default="https://bag.basisregistraties.overheid.nl/api/v1/"
            ),
        ),
    ]
