# Generated by Django 2.2.9 on 2020-03-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0003_auto_20200304_1351")]

    operations = [
        migrations.AddField(
            model_name="bingconfig",
            name="bag_api_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="API key"),
        )
    ]
