# Generated by Django 2.2.1 on 2019-05-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0003_bingconfig")]

    operations = [
        migrations.AddField(
            model_name="bingconfig",
            name="organisatie_rsin",
            field=models.CharField(
                default="002220647", max_length=9, verbose_name="RSIN organisatie"
            ),
        )
    ]
