# Generated by Django 2.2.1 on 2019-05-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0003_auto_20190514_1009"),
        ("config", "0004_bingconfig_organisatie_rsin"),
    ]

    operations = [
        migrations.RemoveField(model_name="apiconfig", name="drc_api_root"),
        migrations.RemoveField(model_name="apiconfig", name="drc_client_id"),
        migrations.RemoveField(model_name="apiconfig", name="drc_secret"),
        migrations.AddField(
            model_name="apiconfig",
            name="brc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
        migrations.AddField(
            model_name="apiconfig",
            name="drc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
        migrations.AddField(
            model_name="apiconfig",
            name="zrc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
        migrations.AddField(
            model_name="apiconfig",
            name="ztc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
    ]
