# Generated by Django 2.2.9 on 2020-03-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0004_bingconfig_bag_api_key")]

    operations = [
        migrations.CreateModel(
            name="AliasCredential",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(max_length=50, unique=True, verbose_name="alias"),
                ),
                (
                    "client_id",
                    models.CharField(max_length=255, verbose_name="client ID"),
                ),
                ("secret", models.CharField(max_length=255, verbose_name="secret")),
            ],
        )
    ]
