# Generated by Django 2.2.9 on 2020-03-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0005_aliascredential")]

    operations = [
        migrations.AddField(
            model_name="bingconfig",
            name="bptl_root",
            field=models.URLField(default="https://bptl.utrechtproeftuin.nl"),
        ),
        migrations.AddField(
            model_name="bingconfig",
            name="bptl_token",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
