# Generated by Django 2.2.1 on 2019-05-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("config", "0005_auto_20190514_1043")]

    operations = [
        migrations.AlterField(
            model_name="apiconfig",
            name="brc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"api_type": "brc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="drc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"api_type": "drc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="zrc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"api_type": "zrc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
        migrations.AlterField(
            model_name="apiconfig",
            name="ztc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"api_type": "ztc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        ),
    ]
