# Generated by Django 2.2.1 on 2019-06-11 11:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0006_auto_20190528_1720")]

    operations = [
        migrations.CreateModel(
            name="RequiredDocuments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "toetswijze",
                    models.CharField(
                        choices=[
                            ("versneld", "versneld"),
                            ("regulier", "regulier"),
                            ("onbekend", "weet ik niet"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="toetswijze",
                    ),
                ),
                (
                    "informatieobjecttypen",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(
                            max_length=1000, verbose_name="informatieobjecttype"
                        ),
                        help_text="Documenttypen",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "verplichte documenten",
                "verbose_name_plural": "verplichte documenten",
            },
        )
    ]
