# Generated by Django 2.2.1 on 2019-06-18 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0007_requireddocuments")]

    operations = [
        migrations.AddField(
            model_name="bingconfig",
            name="minimal_plan_duration",
            field=models.DurationField(
                default=datetime.timedelta(days=7),
                help_text="De minimale tijd die nodig is tussen het moment van indienen aanvraag en de eerst mogelijke vergadering.",
                verbose_name="minimal duration from aanvraag to vergadering",
            ),
        )
    ]
