# Generated by Django 2.2.1 on 2019-07-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0008_bingconfig_minimal_plan_duration")]

    operations = [
        migrations.CreateModel(
            name="URLRewrite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_value",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="from value"
                    ),
                ),
                ("to_value", models.CharField(max_length=100, verbose_name="to value")),
            ],
            options={
                "verbose_name": "URL rewrite",
                "verbose_name_plural": "URL rewrites",
            },
        )
    ]
