# Generated by Django 2.2.1 on 2019-07-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0009_urlrewrite")]

    operations = [
        migrations.AddField(
            model_name="apiconfig",
            name="camunda_root",
            field=models.URLField(
                default="http://localhost:12018/gemeente-utrecht/camunda/",
                help_text="Root URL where camunda is installed.",
                verbose_name="camunda root",
            ),
        )
    ]
