# Generated by Django 2.2.3 on 2019-07-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0010_apiconfig_camunda_root")]

    operations = [
        migrations.AddField(
            model_name="bingconfig",
            name="aanvraag_process_key",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="aanvraag process key"
            ),
        )
    ]
