# Generated by Django 2.2.3 on 2019-07-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("config", "0011_bingconfig_aanvraag_process_key")]

    operations = [
        migrations.AlterField(
            model_name="bingconfig",
            name="aanvraag_process_key",
            field=models.CharField(
                blank=True,
                help_text="Na het indienen van een BInG-aanvraag wordt een instantie van een procesdefinitie met deze key opgestart.",
                max_length=100,
                verbose_name="aanvraag process key",
            ),
        )
    ]
