# Generated by Django 2.2.4 on 2019-08-13 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zgw_consumers", "0003_auto_20190514_1009"),
        ("config", "0012_auto_20190730_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconfig",
            name="nrc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"api_type": "nrc"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zgw_consumers.Service",
            ),
        )
    ]
