# Generated by Django 2.2.1 on 2019-07-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("camunda", "0001_initial")]

    operations = [
        migrations.RenameModel(old_name="ProcessModel", new_name="Deployment"),
        migrations.AlterModelOptions(
            name="deployment",
            options={
                "verbose_name": "deployment",
                "verbose_name_plural": "deployments",
            },
        ),
    ]
