# Generated by Django 2.2.1 on 2019-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("camunda", "0002_auto_20190729_1643")]

    operations = [
        migrations.CreateModel(
            name="ProcessDefinition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camunda_id",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="camunda id"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        editable=False, max_length=100, verbose_name="key"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        editable=False, max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="version"
                    ),
                ),
            ],
            options={
                "verbose_name": "process definition",
                "verbose_name_plural": "process definitions",
            },
        )
    ]
