# Generated by Django 2.2 on 2019-04-23 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("projects", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        )
    ]
