# Generated by Django 2.2 on 2019-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0002_project_created")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="toetswijze",
            field=models.CharField(
                choices=[
                    ("versneld", "versneld"),
                    ("regulier", "regulier"),
                    ("onbekend", "weet ik niet"),
                ],
                default="onbekend",
                max_length=20,
                verbose_name="toetswijze",
            ),
            preserve_default=False,
        )
    ]
