# Generated by Django 2.2.1 on 2019-05-28 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_remove_meeting_projects"),
        ("projects", "0005_project_zaak"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="meeting",
            field=models.ForeignKey(
                blank=True,
                help_text="Specify during which meeting the project will be discussed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="meetings.Meeting",
                verbose_name="meeting",
            ),
        )
    ]
