# Generated by Django 2.2.1 on 2019-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0006_project_meeting")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="planfase",
            field=models.CharField(
                choices=[
                    ("spve/ipve", "SPvE/IPvE"),
                    ("fo", "FO"),
                    ("vo", "VO"),
                    ("do", "DO"),
                    ("onbekend", "weet ik niet"),
                ],
                default="onbekend",
                max_length=20,
                verbose_name="planfase",
            ),
            preserve_default=False,
        )
    ]
