# Generated by Django 2.2.3 on 2019-07-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0007_project_planfase")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="camunda_process_instance_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                unique=True,
                verbose_name="process instance ID",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="camunda_process_instance_url",
            field=models.URLField(
                blank=True, unique=True, verbose_name="process instance URL"
            ),
        ),
    ]
