# Generated by Django 2.2.3 on 2019-08-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0008_auto_20190730_1817")]

    operations = [
        migrations.AddField(
            model_name="projectattachment",
            name="celery_task_id",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="celery task id"
            ),
        )
    ]
