# Generated by Django 2.2.1 on 2019-05-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projects", "0005_project_zaak")]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(verbose_name="start")),
                ("end", models.DateTimeField(verbose_name="start")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "zaak",
                    models.URLField(
                        blank=True, editable=False, max_length=1000, verbose_name="zaak"
                    ),
                ),
                ("projects", models.ManyToManyField(blank=True, to="projects.Project")),
            ],
            options={"verbose_name": "meeting", "verbose_name_plural": "meetings"},
        )
    ]
