# Generated by Django 2.2.1 on 2019-05-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("meetings", "0001_initial")]

    operations = [migrations.RemoveField(model_name="meeting", name="projects")]
