# Generated by Django 2.2.3 on 2019-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("meetings", "0002_remove_meeting_projects")]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="end",
            field=models.DateTimeField(verbose_name="end"),
        )
    ]
