# Generated by Django 2.2.1 on 2019-07-23 12:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Uniquely identifying resource URL",
                        unique=True,
                        verbose_name="url",
                    ),
                ),
                (
                    "resource",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="resource"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
            ],
            options={
                "verbose_name": "cached resource",
                "verbose_name_plural": "cached resources",
            },
        )
    ]
